service: laravel-api

provider:
    name: aws
    region: ap-northeast-1
    environment:
        APP_ENV: production
    iam:
        role:
            statements:
                - Effect: Allow
                  Action: s3:*
                  Resource:
                      - !Sub '${Storage.Arn}'
                      - !Sub '${Storage.Arn}/*'

package:
    patterns:
        - '!node_modules/**'
        - '!resources/assets/**'
        - '!tests/**'

functions:
    api:
        handler: public/index.php
        runtime: php-83-fpm
        timeout: 28
        events:
            - httpApi: '*'
        layers:
            - ${bref-extra:pgsql-php-83}
    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720
        layers:
            - ${bref-extra:pgsql-php-83}

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

resources:
    Resources:
        Storage:
            Type: AWS::S3::Bucket
